[build]
# target = "x86_64-pc-windows-gnu"
target = "x86_64-unknown-linux-musl"
rustflags = ["-C", "target-feature=+crt-static", "-Z", "remap-cwd-prefix="]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]